version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: catcare-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catcare_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - catcare-net

  php:
    image: php:8.2-apache
    container_name: catcare-php
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - mysql
    networks:
      - catcare-net
    command: >
      bash -c "docker-php-ext-install mysqli && apache2-foreground"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: catcare-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: 12345
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - catcare-net

volumes:
  mysql-data:

networks:
  catcare-net: